<?php

namespace DTR\DTRBundle\Repository;
use Doctrine\ORM\EntityRepository;
use DTR\DTRBundle\Entity\Event;
use DTR\DTRBundle\Entity\User;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends EntityRepository
{
    public function findByEventUser(Event $event, User $user)
    {
        return $this
            ->getEntityManager()
            ->createQuery('SELECT m FROM DTRBundle:Member m WHERE m.event = :event AND m.user = :user')
            ->setParameter('event', $event)
            ->setParameter('user', $user)
            ->getOneOrNullResult();
    }

    public function findParticipations(User $user)
    {
        return $this
            ->getEntityManager()
            ->createQuery('SELECT m FROM DTRBundle:Member m JOIN m.event e WHERE m.user = :user')
            ->setParameter('user', $user)
            ->getResult();
    }
}
